# Generated by Django 5.2 on 2025-05-15 08:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossDockTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result_url', models.URLField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('supplier_group', models.CharField(blank=True, choices=[('Группа для проценки ТРЕШКА', 'Группа для проценки ТРЕШКА'), ('ОПТ-2', 'ОПТ-2')], help_text='Supplier group used for this task', max_length=255, null=True)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who created this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cross_dock_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='cross_dock__status_87f0ba_idx'), models.Index(fields=['created_at'], name='cross_dock__created_0899fc_idx'), models.Index(fields=['supplier_group'], name='cross_dock__supplie_66846e_idx')],
            },
        ),
    ]
