# Generated by Django 5.2 on 2025-05-17 11:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_dock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossdocktask',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(help_text='Comment text')),
                ('task', models.ForeignKey(help_text='Task this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cross_dock.crossdocktask')),
                ('user', models.ForeignKey(blank=True, help_text='User who created this comment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cross_dock_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task'], name='cross_dock__task_id_4e72da_idx'), models.Index(fields=['user'], name='cross_dock__user_id_5b0076_idx'), models.Index(fields=['created_at'], name='cross_dock__created_6f7e0d_idx')],
            },
        ),
    ]
