# Generated by Django 5.2 on 2025-05-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_dock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crossdocktask',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='crossdocktask',
            name='input_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='crossdocktask',
            name='platforms',
            field=models.JSONField(default=dict),
        ),
        migrations.AddIndex(
            model_name='crossdocktask',
            index=models.Index(fields=['status'], name='cross_dock__status_87f0ba_idx'),
        ),
        migrations.AddIndex(
            model_name='crossdocktask',
            index=models.Index(fields=['created_at'], name='cross_dock__created_0899fc_idx'),
        ),
    ]
