# Generated by Django 5.2 on 2025-09-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
